// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:PokeStar.Modules.RoleCommand.Role(Discord.IGuildUser,System.String)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:PokeStar.Modules.BasicCommands.Ping~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:PokeStar.Modules.RoleCommand.Role(Discord.IGuildUser,System.String)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:PokeStar.ConnectionInterface.DatabaseConnector.GetRaidBoss(System.String)~PokeStar.DataModels.RaidBoss")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:PokeStar.ConnectionInterface.DatabaseConnector.GetRaidBoss(System.String)~PokeStar.DataModels.RaidBoss")]
[assembly: SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Pending>", Scope = "member", Target = "~M:PokeStar.ConnectionInterface.DatabaseConnector.GetRaidBoss(System.String)~PokeStar.DataModels.RaidBoss")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:PokeStar.ConnectionInterface.DatabaseConnector.GetRaidBossWeather(PokeStar.DataModels.RaidBoss@)")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:PokeStar.ConnectionInterface.DatabaseConnector.GetWeather(System.Collections.Generic.List{System.String})~System.Collections.Generic.List{System.String}")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:PokeStar.ConnectionInterface.DatabaseConnector.GetWeather(System.Collections.Generic.List{System.String})~System.Collections.Generic.List{System.String}")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:PokeStar.ConnectionInterface.DatabaseConnector.GetTypeRelation(System.Collections.Generic.List{System.String},System.Boolean)~System.Collections.Generic.List{System.String}")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:PokeStar.ConnectionInterface.DatabaseConnector.GetTypeRelation(System.Collections.Generic.List{System.String},System.Boolean)~System.Collections.Generic.List{System.String}")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:PokeStar.ConnectionInterface.DatabaseConnector.GetPokemon(System.String)~PokeStar.DataModels.Pokemon")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:PokeStar.ConnectionInterface.DatabaseConnector.GetPokemon(System.String)~PokeStar.DataModels.Pokemon")]
[assembly: SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Pending>", Scope = "member", Target = "~M:PokeStar.ConnectionInterface.DatabaseConnector.GetPokemon(System.String)~PokeStar.DataModels.Pokemon")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:PokeStar.ConnectionInterface.DatabaseConnector.GetMoves(System.String,System.Boolean)~System.Collections.Generic.List{PokeStar.DataModels.Move}")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:PokeStar.ConnectionInterface.DatabaseConnector.GetMoves(System.String,System.Boolean)~System.Collections.Generic.List{PokeStar.DataModels.Move}")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:PokeStar.ConnectionInterface.DatabaseConnector.GetTypeRelations(System.Collections.Generic.List{System.String},System.Boolean)~System.Collections.Generic.List{System.String}")]
[assembly: SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Pending>", Scope = "member", Target = "~M:PokeStar.ConnectionInterface.DatabaseConnector.GetWeather(System.Collections.Generic.List{System.String})~System.Collections.Generic.List{System.String}")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:PokeStar.ConnectionInterface.DatabaseConnector.GetTypeRelations(System.Collections.Generic.List{System.String},System.Boolean)~System.Collections.Generic.List{System.String}")]
[assembly: SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Pending>", Scope = "member", Target = "~M:PokeStar.ConnectionInterface.DatabaseConnector.GetMoves(System.String,System.Boolean)~System.Collections.Generic.List{PokeStar.DataModels.Move}")]
[assembly: SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Pending>", Scope = "member", Target = "~M:PokeStar.ConnectionInterface.DatabaseConnector.GetTypeRelations(System.Collections.Generic.List{System.String},System.Boolean)~System.Collections.Generic.List{System.String}")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:PokeStar.Modules.SetupCommand.SetEmotes(Discord.WebSocket.SocketGuild)")]
